### ISSUE TITLE
Event issue

### ISSUE THREAD

**Issue by d333s** [7isenko/UltraHardcore#1]
Recently encountered it, when a player shot a bow from a horse.

`[00:46:31 ERROR]: Could not pass event EntityShootBowEvent to UltraHardcore v1.0
java.lang.ClassCastException: org.bukkit.craftbukkit.v1_16_R1.entity.CraftSpectralArrow cannot be cast to org.bukkit.entity.Arrow
        at io.github._7isenko.ultrahardcore.mobs.HomingArrowMaker.onShot(HomingArrowMaker.java:21) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor56.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-101]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-101]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-101]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-101]
        at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callEntityShootBowEvent(CraftEventFactory.java:537) ~[patched_1.16.1.jar:git-Paper-101]
        at net.minecraft.server.v1_16_R1.ItemBow.a(ItemBow.java:55) ~[patched_1.16.1.jar:git-Paper-101]
        at net.minecraft.server.v1_16_R1.ItemStack.a(ItemStack.java:607) ~[patched_1.16.1.jar:git-Paper-101]
        at net.minecraft.server.v1_16_R1.EntityLiving.releaseActiveItem(EntityLiving.java:3245) ~[patched_1.16.1.jar:git-Paper-101]
        at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1379) ~[patched_1.16.1.jar:git-Paper-101]
        at net.minecraft.server.v1_16_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.16.1.jar:git-Paper-101]
        at net.minecraft.server.v1_16_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.16.1.jar:git-Paper-101]
        at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-101]
        at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-101]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-101]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-101]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-101]
        at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136) ~[patched_1.16.1.jar:git-Paper-101]
        at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.1.jar:git-Paper-101]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-101]
        at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.1.jar:git-Paper-101]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004) ~[patched_1.16.1.jar:git-Paper-101]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-101]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]`

Also, is it possible for you to add a config file for us to be able to disable certain arrow effects / damage item drop rates.

**Comment by 7isenko** [comment]
I'll work on it. Thanks

**Comment by 7isenko** [comment]
https://github.com/7isenko/UltraHardcore/releases/tag/1.1
Fixed.
